#!/usr/bin/perl

use strict;
use warnings;

{
  package MyWebServer;

  use HTTP::Server::Simple::CGI;
  use base qw(HTTP::Server::Simple::CGI);
  use JSON;
  use Data::Dumper;

  sub handle_request {
    my $self = shift;
    my $cgi  = shift;

    unless ($cgi->request_method() eq 'POST' && $cgi->path_info() eq '/' && (my $hook = JSON->new->utf8->decode(scalar $cgi->param('POSTDATA')))) {
      print "HTTP/1.1 400 Bad Request\r\n", $cgi->header, "400 Bad Request\n";
    } else {
      print "HTTP/1.1 200 OK\r\n", $cgi->header, "200 OK\n";
      warn Dumper($hook), "\n";
    }
  }
}

my $pid = MyWebServer->new(8089)->run(); #background();
print "pid = $pid\n";
