#!/usr/bin/perl

use strict;
use warnings;

{
  package MyWebServer;

  use HTTP::Server::Simple::CGI;
  use base qw(HTTP::Server::Simple::CGI);

  sub handle_request {
    my $self = shift;
    my $cgi  = shift;

    print "HTTP/1.0 200 OK\r\n", $cgi->header, $cgi->start_html("200 OK"), $cgi->h1("200 OK"), $cgi->end_html;
  }
}

my $pid = MyWebServer->new(8089)->run(); #background();
print "pid = $pid\n";
